version: '3'
services:
  mongodb:
   image: mongo:latest
  interlok:
    build:
      context: .
      dockerfile: Dockerfile
    image: adaptris/interlok-mongodb-docker:latest
    depends_on:
      - mongodb
    ports:
      - 8080:8080
